### PR TITLE
qpOASES updated to version 3.2.0

### PR DESCRIPTION
**Pull request by gabrielenava**
I updated qpOASES to version 3.2.0 with the hope of solving [this issue](https://github.com/robotology-dependencies/qpOASES/issues/4). I did two different commits:

- https://github.com/gabrielenava/qpOASES/commit/407c77adaba8397d7281c2c32584b878dc070cff is the original qpOASES 3.2.0 as downloaded.

- https://github.com/gabrielenava/qpOASES/commit/267c1c0b8c1f49caa07879a66926c2abfc726b5c are local modifications to comply with our workflow.

I would like to proper test the new qpOASES before merging.

### CODE REVIEW

**Comment by gabrielenava** [comment]
I tested the update in simulation. Nothing changed from the controllers point of view. Still, tests on the robot are missing.

**Comment by traversaro** [comment]
We typically use `[WIP]` for avoiding  accidental merges.

**Comment by gabrielenava** [comment]
Tested on `iCubGenova02`. No issues to report. The behaviour of the robot was (qualitative) as before the update. I think we can merge this PR. Only question: is qpOASES used only for the balancing controllers?

**Comment by traversaro** [comment]
+1 to merging this PR. 

> Only question: is qpOASES used only for the balancing controllers?

https://github.com/search?l=Matlab&q=org%3Arobotology+qpOASES&type=Code 
https://github.com/search?l=Matlab&q=org%3Arobotology-playground+qpOASES&type=Code

As OpenSOT uses another fork, I guess the answer is yes.

**Comment by gabrielenava** [comment]
Ok, merging then!

**Pull request merged**
